### ISSUE TITLE
Bring Student view into line with student grade summary

### ISSUE THREAD

**Issue by payten** [steveswinsburg/gradebookNG#187]
Match the “Student Review Mode”.

**Comment by steveswinsburg** [comment]
Done in #189

**Comment by kyleblythe** [comment]
Hi @steveswinsburg ,

Sorry if this is a repeat of what we discussed last week, but noticed the "ready to test" label on this one. We're still seeing the following "Something went wrong" error message when testing these permissions from the TA's view:

http://www.screencast.com/t/saKaD6rr

**Comment by payten** [comment]
I've created a new issue to investigate how we can expose the category score and weight to the student. Currently the permissions on the Gradebook service don't allow a student to access this information #202.

**Comment by kyleblythe** [comment]
Hi @payten,

The category weighting is looking great, both in the instructor's "Student Review Mode" and the actual student view. It looks like the instructor "Student Review Mode" is capable of displaying an "N/A" category subtotal percentage if there are items that are not included in course grade calculations. Can we replicate that in the student view?

Additionally:
- Looks like a "/100" appears even when no scores are provided for an item:

![2015-09-10_15-15-04](https://cloud.githubusercontent.com/assets/11447474/9798408/bc6c1f1e-57ce-11e5-81f6-946193863c3b.png)

This appears in both the "Student Review Mode" and the actual student view.
- The category subtotal score should appear if all items in the category are released (as they are in GB1). Right now the subtotals are not appearing for students.

I can create these as a separate issue, as they apply to both the "Student Review Mode" and the student view.

**Comment by payten** [comment]
Hey @kyleblythe.  I think this one might be sorted now category averages are correctly displaying :)

**Comment by kyleblythe** [comment]
Student view's looking great, @payten . Thanks!
