### ISSUE TITLE
Import / Export process not recognizing updated scores, provides an error when importing new items.

### ISSUE THREAD

**Issue by kyleblythe** [steveswinsburg/gradebookNG#39]
When downloading a spreadsheet template, modify / add scores for a column. When importing that csv file back into the system, Import / Export does not recognize updated scores - all item statuses will be listed as "N/A." Upon completing the process, the updated scores are not present in the spreadsheet.

If a new item is manually added to the spreadsheet export, attempting to import that back into the system causes an unexpected runtime exception error message: http://www.screencast.com/t/iJuXtTtm

**Comment by maurercw** [comment]
Let's see if PR #40 addresses this issue.

**Comment by steveswinsburg** [comment]
@kyleblythe could you please re-test? I've merged in PR #40.

**Comment by kyleblythe** [comment]
Hi @steveswinsburg and @maurercw,

Ok, looks like the issue is still occurring. I tested with a few different conditions, and each time I clicked "Next" I got an Unexpected RunTime Exception: http://www.screencast.com/t/HMDNjHw57qe

The conditions were:
New grade scores within an item column
New comments in an item's comment column
Modified title of downloaded template, with no changes to spreadsheet content
No modifications whatsoever

**Comment by maurercw** [comment]
Hmm.  Is this running out in the world anywhere?  Just trying to rule out
my environment and see if you had something special in the gradebook setup
that I didn't.  I'll take a peek again tonight.

Chris

**Comment by maurercw** [comment]
Ah, I think I see the issue.  Bitten by copy/paste I believe!

**Comment by maurercw** [comment]
Let's try again with PR #41.

**Comment by steveswinsburg** [comment]
Ok that's in.

**Comment by steveswinsburg** [comment]
Hi @kyleblythe, do you think you could test this out again? Let me know if there are any issues.

**Comment by kyleblythe** [comment]
Hi @steveswinsburg and @maurercw,

I tried out a few different scenarios for this. Results (and steps to reproduce) are below. To note, I did the testing in this site: https://sandboxclasses1.home.nyu.edu/portal/site/0126c41b-71b2-468b-9550-b6e06d1793d4

Importing csv with modified grade entry (resulted in incorrect statuses and, when attempting to complete import, a Runtime Exception screen):

1) Downloaded Full csv template.
2) Modified template to include add'l scores (in this case, I added a few scores to the "Midterm" Item") and saved.
3) When selecting the modified csv file in the GB and clicking "Next," I got the following selection screen:
http://www.screencast.com/t/FXmVRUn194Tj
Note: Homework 2, Homework 3, and Homework 4 were not modified, yet showed up with statuses of "Update"
4) Selected "Midterm" and clicked "Next."
5) successfully reached the confirmation screen. When I clicked "Finish," I got the following error message:
http://www.screencast.com/t/2DL3HSb666A

Importing csv with new comments but no grade modifications (resulted in incorrect statuses and, when attempting to complete import, a Runtime Exception screen):

1) Downloaded Full csv template.
2) Modified template to include only include add'l comments in an item's Comments column (in this case, "Homework 4 Comments") and saved.
3) When selecting the modified csv file in the GB and clicking "Next," I got the following selection screen:
http://www.screencast.com/t/l2DbQBfN0
Note: Homework 2, Homework 3, and Homework 4 grade scores were not modified, yet showed up with statuses of "Update"
4) Selected "Homework 4" and "Homework 4 Comments" and clicked "Next."
5) Successfully reached the confirmation screen. When I clicked "Finish," I got the following error message:
http://www.screencast.com/t/42ytBB6Ol0LQ

Importing csv with new item/comment column added, but no modifications to existing content (resulted in immediate Runtime Exception screen):

1) Downloaded Full csv template.
2) Added two new columns to csv file ("Midterm 2" and "*/ Midterm 2 Comments */") and saved. Entered no grade data.
3) When selecting the modified csv file in the GB and clicking "Next," I received the following Runtime Exception error screen:
http://www.screencast.com/t/aTMPodOP2f

**Comment by maurercw** [comment]
Thanks for the extra details.  I'll take a look.

Chris

**Comment by steveswinsburg** [comment]
Hey @maurercw have you had a chance to look into this one? cheers.

**Comment by maurercw** [comment]
Looking into it now.

Chris

**Comment by maurercw** [comment]
I think I've got fixes for most of these issues about ready.  For the last one you mention @kyleblythe , it seems like you added new assignments by just adding a header but not adding corresponding (empty) items for each student.  What should the import do?  Just assume that the missing values were null and set nothing or complain of an improperly formatted csv since there aren't enough fields?

**Comment by maurercw** [comment]
Oh, now that I'm debugging (and looking more at the logs) it looks like there is an exception being thrown (2015-05-18 22:27:27,288 ERROR http-nio-8080-exec-36 org.sakaiproject.gradebookng.business.helpers.ImportGradesHelper - Error reading imported file: class java.lang.ArrayIndexOutOfBoundsException : 20) so that may answer my question!  I'll see about handling that a bit more gracefully and passing the error on to the UI.

**Comment by maurercw** [comment]
Actually, I can probably just leave the value empty.  Which ever you guys thing is best.

**Comment by steveswinsburg** [comment]
Yeah I think it should be pretty tolerant.  There is a summary screen of
what's going to happen so once uploaded the instructor can see if that's
what they wanted.

sent from my mobile device

**Comment by maurercw** [comment]
Ok, see how PR #86 looks.  That should (hopefully) at least get rid of the errors.  Still looking to see if I can reproduce the cases of the status not being determined correctly.

**Comment by kyleblythe** [comment]
Hi @maurercw,

In our Sandbox instance, when I try to download the "Full" Gradebook in any site, I am getting an Unexpected Runtime Exception:

http://www.screencast.com/t/IFv2goVlsXWS

**Comment by maurercw** [comment]
@kyleblythe Does that error happen after you apply my change in PR #86 ?  I fixed some stuff in there, but if you still get errors afterwards, then I need to look (and test) some more!

**Comment by steveswinsburg** [comment]
Ugh I thought I merged that, so Kyle wouldnt have the change until now. Sorry. I've put it in now so it should get into the nightly for verification.

**Comment by kyleblythe** [comment]
Hi @maurercw,

I tested again, and things are running much more smoothly! I'm now able to walk through the entire import process, and new GB items are able to be successfully created.

A few things I'm noticing, however:

1) The status screen is still showing inaccurate "Update" statuses when looking to an uploaded spreadsheet. Specifically, it seems like every GB item has an "Update" status, regardless of whether they have been updated. Comment column statuses are working correctly, reflecting "NA" or "Update" when appropriate.

2) Imported grade values/comments are still failing to import. When I add a grade value to an item and text to a comment column, the scores/text do not get reflected upon successfully completing the import.

**Comment by steveswinsburg** [comment]
I think I found the error with this @maurercw. 

The import is doing this:

```
businessService.saveGrade(processedGradeItem.getItemId(), processedGradeItemDetail.getStudentId(),
processedGradeItemDetail.getGrade(),
 processedGradeItemDetail.getComment());
```

The business service methods are:

```
    public GradeSaveResponse saveGrade(final Long assignmentId, final String studentUuid, final String oldGrade, final String newGrade);

    public GradeSaveResponse saveGrade(final Long assignmentId, final String studentUuid, String oldGrade, String newGrade, final String comment);
```

The import code is using the first signature, so its putting he grade into the oldGrade slot and the comment into the new Grade slot, and the comment is being set to null.

I'll add you a new business service method.

**Comment by steveswinsburg** [comment]
Ok I've adjusted that method signature to actually do what your code expects. Can you give it a try? it may need a bit more refactoring.

**Comment by kyleblythe** [comment]
Hi @steveswinsburg and @maurercw ,

After some testing, it looks like updated grades are still failing to be reflected in the Gradebook following import.

I downloaded an up-to-date GB from this site: https://sandboxclasses1.home.nyu.edu/portal/site/0126c41b-71b2-468b-9550-b6e06d1793d4

I then updated all scores for item "Week 1 Part," as seen in the following:
http://www.screencast.com/t/CX56rdap7kI

Upon uploading the spreadsheet, selecting the item for import, and completing the import process, however, the resulting Gradebook displayed as follows:
http://www.screencast.com/t/5Inu2ZAj

I've tested a few different times, with different items (including new items, which do get successfully created), and can confirm that the scores aren't appearing following import.

**Comment by maurercw** [comment]
May finally have this one figured out.  Sheesh.  This one was hiding!

**Comment by maurercw** [comment]
@steveswinsburg  give PR #114 a try!

**Comment by maurercw** [comment]
Bah, I think the comments aren't coming through.  Still closer though!

**Comment by steveswinsburg** [comment]
Ok that is merged :+1:

**Comment by steveswinsburg** [comment]
@maurercw are we good to test this one?

**Comment by maurercw** [comment]
It should save the grades ok, but not the comments yet.  Looking into the comments part now.

**Comment by maurercw** [comment]
@steveswinsburg Looking at the saveGrade method in the GradebookNgBusinessService, it won't take into account adding only a new comment with an unchanged grade.  Is that what we want?  I think I have my changes in place to actually call the service in a reasonable way.  See PR #126 for the changes in the model to handle the comments from the import side.  Do you want to handle the service changes (or are you okay with not updating a comment if there were no grade changes)?  Or do you want me to try to make the service changes?

**Comment by steveswinsburg** [comment]
I can make the service changes, though I wonder if there is no grade it could instead call     `updateAssignmentGradeComment(final long assignmentId, final String studentUuid, final String comment)` ? That will touch just the comment. Would that work?

**Comment by maurercw** [comment]
It all depends on where you want the logic to check if the grade needs saving or if the comment needs saving.  If you want to just add a comment check in your `saveGrade` method, then that could call off to the `updateAssignmentGradeComment` instead?

**Comment by steveswinsburg** [comment]
I reckon have it up in the import logic to call the appropriate method. We have a response that comes back saying no change, but really there is a change being made, so that would be need to be reworked.

**Comment by maurercw** [comment]
@steveswinsburg See if PR #134 does the trick.

**Comment by steveswinsburg** [comment]
I think we are almost there.

If I update a grade and comment for an assignment, then that one is marked with changes and the others are 'No change'. :white_check_mark: 
Also, the grades appear to be imported correctly and when I go back to the Gradebook they are updated :white_check_mark: 

But I found two bugs :cry:

**1** if a grade is over limit (ie 200 in a 100 point assignment) then I get a red error when importing, however the update goes through and the grades are saved.

Maybe instead of an error, a warning could be presented saying some grades were over limit perhaps. Or not worry about a warning at all. @kyleblythe WDYT?

**2** If I add a new item in the CSV, when I go to the new item screen and click Finish I get the stacktrace:

```
Caused by: java.lang.IllegalArgumentException: null parameter passed to getAssignmentScoreString
    at org.sakaiproject.component.gradebook.GradebookServiceHibernateImpl.getAssignmentScoreString(GradebookServiceHibernateImpl.java:2040)
    at sun.reflect.GeneratedMethodAccessor495.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:317)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:183)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:150)
    at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:96)
    at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:260)
    at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:94)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
    at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:204)
    at com.sun.proxy.$Proxy26.getAssignmentScoreString(Unknown Source)
    at org.sakaiproject.gradebookng.business.GradebookNgBusinessService.saveGrade(GradebookNgBusinessService.java:267)
    at org.sakaiproject.gradebookng.business.GradebookNgBusinessService.saveGrade(GradebookNgBusinessService.java:243)
```

This page needs some love and I'll be reworking it soon, but is there some required parameter missing?

**Comment by maurercw** [comment]
I'll take a look at 2 now...  
I have no idea why that page looks so terrible!  It might be a simple css issue relating to the way that content is embedded?  I'll try to take a look and see if anything obvious pops up.

**Comment by maurercw** [comment]
Is the non-import version of that page used in a popup?

**Comment by maurercw** [comment]
Grr...my life would be easier if the GradebookService's addAssignment method returned the id of the created assignment.  Any chance we can make that change?  I guess I could do it and make a PR!

**Comment by steveswinsburg** [comment]
Yeah that page is the same as add gradebook item, but needs to updated to
be like edit gradebook item which looks nicer and works. I had that on my
list if you are out of hours?

Feel free to submit PR for that gradebook service change if we need it.

sent from my mobile device

**Comment by maurercw** [comment]
We don't "need" it, but it'd save me an extra service call to get all the assignments again.  I'll take a quick look and see if I can do a PR for it.

**Comment by maurercw** [comment]
FYI, submitted sakai PR in case you want to review and merge: https://github.com/sakaiproject/sakai/pull/779

**Comment by steveswinsburg** [comment]
OK it's in.

sent from my mobile device

**Comment by maurercw** [comment]
Cool, see if PR #136 now does the trick for the import error.

**Comment by steveswinsburg** [comment]
Hey @kyleblythe  I think sandbox will need a rebuild for you to get this as it is an upstream sakai mod. @payten are you able to kick this one off? Everything merged on both sakai and gbng fronts. :+1:

**Comment by steveswinsburg** [comment]
Hey @kyleblythe could we get one final pass on this one to close this out? Cheers :smile_cat:

**Comment by kyleblythe** [comment]
Success! New GB items are successfully added, scores/comments are added/edited, and statuses are accurately reflected.

CSV file can also be successfully renamed on the client's side, and import will still occur as expected.

We're good to go on this.

**Comment by steveswinsburg** [comment]
Nice one. Thanks @kyleblythe and @maurercw :)
